# Generated by Django 4.1.1 on 2022-09-25 15:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Category')),
                ('slug', models.CharField(max_length=200, verbose_name='Category slug')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foods.category')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Food Price')),
                ('disc', models.CharField(max_length=200, verbose_name='Food Price')),
                ('slug', models.CharField(max_length=200, verbose_name='Food slug')),
                ('price', models.FloatField(verbose_name='Food Price')),
                ('old_price', models.FloatField(verbose_name='Food Price')),
                ('is_avaible', models.BooleanField(verbose_name='Food Avaible')),
                ('created_at', models.DateTimeField(verbose_name='Food Created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.category')),
            ],
        ),
    ]
