# Generated by Django 4.1.1 on 2022-09-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='static/default-food.jpg', upload_to='media', verbose_name='Food Image'),
        ),
    ]
