# Generated by Django 4.1.1 on 2022-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default/default-food.jpg', upload_to='foods/', verbose_name='Food Image'),
        ),
    ]
