# Generated by Django 4.1.1 on 2022-09-26 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 1, 56, 187644), verbose_name='Food Created at'),
        ),
        migrations.AlterField(
            model_name='food',
            name='disc',
            field=models.CharField(max_length=200, verbose_name='Food disc'),
        ),
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Food title'),
        ),
    ]
