# Generated by Django 4.1.1 on 2022-09-26 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_food_created_at_alter_food_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 0, 25, 450), verbose_name='Food Created at'),
        ),
    ]
