# Generated by Django 4.1.1 on 2022-09-29 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_alter_food_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 22, 48, 21, 624352), verbose_name='Food Created at'),
        ),
    ]
