# Generated by Django 4.1.1 on 2022-09-30 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_alter_food_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=60, verbose_name='Category slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 45, 31, 144049), verbose_name='Food Created at'),
        ),
    ]
