# Generated by Django 4.1.1 on 2022-10-03 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_alter_food_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 20, 41, 36, 193243), verbose_name='Food Created at'),
        ),
    ]
