# Generated by Django 4.1.1 on 2022-09-26 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0007_alter_food_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Code Postal')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 0, 25, 3448), verbose_name='Ordred at')),
                ('constumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Constumer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(verbose_name='Quqntity')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food', verbose_name='Ordred Food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order')),
            ],
        ),
    ]
