# Generated by Django 4.1.1 on 2022-09-30 22:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0011_alter_category_slug_alter_category_title_and_more'),
        ('orders', '0004_alter_order_created_at_alter_orderline_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='constumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Constumer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 45, 31, 144049), verbose_name='Ordred at'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foods.food', verbose_name='Ordred Food'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_of_line', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quant',
            field=models.PositiveSmallIntegerField(max_length=2, verbose_name='Quantity'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250, verbose_name='Strre')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('postal_code', models.PositiveSmallIntegerField(max_length=5, verbose_name='Code Postal')),
                ('constumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Constumer')),
            ],
        ),
    ]
