# Generated by Django 4.1.1 on 2022-10-01 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_location_remove_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.PositiveSmallIntegerField(verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 16, 35, 33, 106044), verbose_name='Ordred at'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quant',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
    ]
