# Generated by Django 4.1.1 on 2022-10-03 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_created_at_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 20, 41, 36, 195280), verbose_name='Ordred at'),
        ),
    ]
